### ISSUE TITLE
undefined reference 

### ISSUE THREAD

**Issue by SALAH30** [snap-stanford/snap#138]
i'm trying to use SNAP, with C++, I'm using CLion 
when i add #include "Snap.h"
i had this problem : 
|
|
|
|
CMakeFiles/CNI.dir/main.cpp.o: In function `TRStr::~TRStr()':
C:/Users/salah-eddine.boukhet/Documents/ETUDE/PFE/subgraph-isomorphism-searche-implementation/snap-master/glib-core/dt.h:366: undefined reference to `ExeStop(char const*, char const*, char const*, char const*, int const&)'
C:/Users/salah-eddine.boukhet/Documents/ETUDE/PFE/subgraph-isomorphism-searche-implementation/snap-master/glib-core/dt.h:366:(.text$_ZN5TRStrD1Ev[_ZN5TRStrD1Ev]+0x72): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ExeStop(char const*, char const*, char const*, char const*, int const&)'
CMakeFiles/CNI.dir/main.cpp.o: In function `TRStr::UnRef()':
C:/Users/salah-eddine.boukhet/Documents/ETUDE/PFE/subgraph-isomorphism-searche-implementation/snap-master/glib-core/dt.h:379: undefined reference to `ExeStop(char const*, char const*, char const*, char const*, int const&)'
C:/Users/salah-eddine.boukhet/Documents/ETUDE/PFE/subgraph-isomorphism-searche-implementation/snap-master/glib-core/dt.h:379:(.text$_ZN5TRStr5UnRefEv[_ZN5TRStr5UnRefEv]+0x50): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ExeStop(char const*, char const*, char const*, char const*, int const&)'
CMakeFiles/CNI.dir/main.cpp.o: In function `TRStr::GetNullRStr()':
C:/Users/salah-eddine.boukhet/Documents/ETUDE/PFE/subgraph-isomorphism-searche-implementation/snap-master/glib-core/dt.h:403: undefined reference to `ExeStop(char const*, char const*, char const*, char const*, int const&)'
C:/Users/salah-eddine.boukhet/Documents/ETUDE/PFE/subgraph-isomorphism-searche-implementation/snap-master/glib-core/dt.h:403:(.text$_ZN5TRStr11GetNullRStrEv[_ZN5TRStr11GetNullRStrEv]+0xa8): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ExeStop(char const*, char const*, char const*, char const*, int const&)'
CMakeFiles/CNI.dir/main.cpp.o: In function `TStr::TStr(char const*)':
C:/Users/salah-eddine.boukhet/Documents/ETUDE/PFE/subgraph-isomorphism-searche-implementation/snap-master/glib-core/dt.h:427: undefined reference to `TStr::GetRStr(char const*)'
C:/Users/salah-eddine.boukhet/Documents/ETUDE/PFE/subgraph-isomorphism-searche-implementation/snap-master/glib-core/dt.h:427:(.text$_ZN4TStrC1EPKc[_ZN4TStrC1EPKc]+0x18): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `TStr::GetRStr(char const*)'
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/CNI.dir/build.make:355: CNI.exe] Error 1
make[2]: *** [CMakeFiles/Makefile2:68: CMakeFiles/CNI.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/CNI.dir/rule] Error 2
make: *** [Makefile:118: CNI] Error 2

**Comment by RubinYao** [comment]
I have the same problem, how to solve?

**Comment by jessemapel** [comment]
@RubinYao I wasn't able to find a solution for this and ended up going with a different graph library.

**Comment by RubinYao** [comment]
@jessemapel thanks for your reply,  can you tell me which graph library did you use, I want to try, thanks again!

**Comment by jessemapel** [comment]
@RubinYao We had a lot of success with boost's graph library.

**Comment by RubinYao** [comment]
@jessemapel thanks.

**Comment by roks** [comment]
@RubinYao Which OS and compiler do you use?

**Comment by RubinYao** [comment]
@roks  I used snap library  under Window 10 with Cygwin with GCC.  After downloading the source code from http://snap.stanford.edu/releases/Snap-5.0.zip and zipping, I run "make all" in the main SNAP directory under Cygwin. Then, I create a new C++ project in Eclipse CDT IDE and set the project property: C/C++ General -> paths and symbols -> includes -> GUN 
 C++ : "C:\cygwin64\home\lenovo\Snap-5.0\snap-adv; C:\cygwin64\home\lenovo\Snap-5.0\snap-core; C:\cygwin64\home\lenovo\Snap-5.0\glib-core;".  After that, run a helloworld cpp like this
`//======================

#include <iostream>

#include "Snap.h";

using namespace std;

int main() {

	cout << "!!!Hello World!!!" << endl; // prints !!!Hello World!!!
	return 0;
}
`
then get the errors:
/home/lenovo/Snap-5.0/glib-core/dt.h:366: undefined reference to `ExeStop(char const*, char const*, char const*, char const*, int const&)'
/home/lenovo/Snap-5.0/glib-core/dt.h:366:(.text$_ZN5TRStrD1Ev[_ZN5TRStrD1Ev]+0x62): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ExeStop(char const*, char const*, char const*, char const*, int const&)'
./src/SNAP.o: In function `TRStr::UnRef()':
/home/lenovo/Snap-5.0/glib-core/dt.h:379: undefined reference to `ExeStop(char const*, char const*, char const*, char const*, int const&)'
/home/lenovo/Snap-5.0/glib-core/dt.h:379:(.text$_ZN5TRStr5UnRefEv[_ZN5TRStr5UnRefEv]+0x40): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ExeStop(char const*, char const*, char const*, char const*, int const&)'
./src/SNAP.o: In function `TRStr::GetNullRStr()':
/home/lenovo/Snap-5.0/glib-core/dt.h:403: undefined reference to `ExeStop(char const*, char const*, char const*, char const*, int const&)'
/home/lenovo/Snap-5.0/glib-core/dt.h:403:(.text$_ZN5TRStr11GetNullRStrEv[_ZN5TRStr11GetNullRStrEv]+0x9e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ExeStop(char const*, char const*, char const*, char const*, int const&)'
./src/SNAP.o: In function `TStr::TStr(char const*)':
/home/lenovo/Snap-5.0/glib-core/dt.h:427: undefined reference to `TStr::GetRStr(char const*)'
/home/lenovo/Snap-5.0/glib-core/dt.h:427:(.text$_ZN4TStrC1EPKc[_ZN4TStrC1EPKc]+0x18): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `TStr::GetRStr(char const*)'
collect2: error: ld returned 1 exit status
make: *** [makefile:47: SNAP.exe] Error 1

then I try the Visual studio 2019 and configure the environment following the steps "SNAP on Windows with Visual Studio", also have the same problem.

**Comment by trevorKirkby** [comment]
I just ran into the same issue on Ubuntu 18.04.4 LTS, using the ordinary GCC that comes out of the box with Ubuntu, compiling pretty much the same program RubinYao tried out, just including "Snap.h" without doing anything else.

**Comment by roks** [comment]
try "cd Snap-5.0/examples/testgraph; make; ./testgraph". This works on our version of Ubuntu 18.04. If the command is successful, you can start with testgraph and modify it for your purpose. It compile command is "g++ -std=c++98 -Wall -O3 -DNDEBUG -fopenmp -o testgraph testgraph.cpp  ../../snap-core/Snap.o -I../../snap-core -I../../snap-adv -I../../glib-core -I../../snap-exp  -lrt'.
